// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Expression struct {
	Body string `json:"body"`
}

type XRange struct {
	Xmin float64 `json:"Xmin"`
	Xmax float64 `json:"Xmax"`
	N    int     `json:"N"`
}
